version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - default
  postgres:
    image: postgres:latest
    user: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      #volumes:
      #- db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/postgres -user=postgres -password=postgres -locations=filesystem:/flyway/sql -connectRetries=10  migrate
    volumes:
      - ${PWD}/pkg/db/migrations/sql:/flyway/sql
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - default
  zookeeper:
    image: 'wurstmeister/zookeeper:3.4.6'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - default
  kafka:
    image: 'wurstmeister/kafka'
    container_name: kafka
    ports:
      - "9092:9092"
      - "8082:8082"
    depends_on:
      - zookeeper
    env_file:
      - kafka.env
    networks:
      - default
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mkulik/testtask2:testtask2
    depends_on:
      - postgres
      - flyway
      - redis
      - kafka
    ports:
      - "9000:9000"
    restart: on-failure
    env_file:
      - .env
    environment:
      - pUrl=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - DB=postgres
      - PASSWORD=postgres
      - USER=postgres
      - PORT=5432
    networks:
      - default