// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommonResponse struct {
	Message string `json:"message"`
}

type EnrichedFio struct {
	Name        string  `json:"name"`
	Surname     string  `json:"surname"`
	Patronymic  *string `json:"patronymic,omitempty"`
	Age         int     `json:"age"`
	Gender      string  `json:"gender"`
	Nationality string  `json:"nationality"`
}

type Fio struct {
	Name       string  `json:"name"`
	Surname    string  `json:"surname"`
	Patronymic *string `json:"patronymic,omitempty"`
}

type FIOResponse struct {
	Name       string  `json:"name"`
	Surname    string  `json:"surname"`
	Patronymic *string `json:"patronymic,omitempty"`
}

type UserU struct {
	ID          string       `json:"id"`
	Fio         *FIOResponse `json:"fio"`
	Age         int          `json:"age"`
	Gender      string       `json:"gender"`
	Nationality string       `json:"nationality"`
}
